### PR TITLE
rebar build without ssh keys fails due to outdated dep libs

### PR DESCRIPTION
**Pull request by elbrujohalcon**
"rebar get-deps" of sumo_db fails if no github ssh keys are set up because some of the dependencies use "git@" url scheme instead of "git://". 
Affected libraries include tirerl 0.1.0 (fixed in master) and shotgun 0.1.4 (fixed in later releases).

### CODE REVIEW

**Comment by elbrujohalcon** [comment]
@Vorticity-Flux there you go… [release 0.3.5](releases/0.3.5) should fix your issue.

**Comment by Vorticity-Flux** [comment]
Thanks a lot! You are fast! =)

Not sure if this deserves any attention but just in case:
```
> rebar update-deps
...
ERROR: Conflicting dependencies for lager: [{"From: shotgun",
                                             {".*",
                                              {git,
                                               "git://github.com/basho/lager.git",
                                               "2.0.3"}}},
                                            {"From: sumo_db",
                                             {".*",
                                              {git,
                                               "git://github.com/basho/lager.git",
                                               "2.1.1"}}},
                                            {"From: worker_pool",
                                             {"2.*",
                                              {git,
                                               "git://github.com/basho/lager.git",
                                               "2.0.3"}}}]
ERROR: Conflicting dependencies for sync: [{"From: shotgun",
                                            {".*",
                                             {git,
                                              "git://github.com/inaka/sync.git",
                                              "0.1"}}},
                                           {"From: tirerl",
                                            {"0.*",
                                             {git,
                                              "git://github.com/inaka/sync.git",
                                              "0.1.3"}}}]
```

**Comment by elbrujohalcon** [comment]
I'll open a github issues for those repos to update their dependencies

**Comment by elbrujohalcon** [comment]
- inaka/shotgub#69
- inaka/worker_pool#23

**Pull request merged**
